import { db } from "./db";
import { categories, products } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existingCategories = await db.select().from(categories);
  if (existingCategories.length > 0) return;

  const cats = await db.insert(categories).values([
    { name: "Pappbecher", slug: "pappbecher", description: "Individuell bedruckte Pappbecher fuer Heissgetraenke", imageUrl: "/images/paper-cups.png" },
    { name: "Plastikbecher", slug: "plastikbecher", description: "Bedruckte Plastikbecher fuer Kaltgetraenke", imageUrl: "/images/plastic-cups.png" },
    { name: "Eisbecher", slug: "eisbecher", description: "Bedruckte Eisbecher in verschiedenen Groessen", imageUrl: "/images/ice-cream-cups.png" },
    { name: "Lebensmittelboxen", slug: "lebensmittelboxen", description: "Bedruckte Takeaway-Boxen fuer alle Speisen", imageUrl: "/images/food-boxes.png" },
    { name: "Papiertueten", slug: "papiertueten", description: "Bedruckte Papiertueten mit Henkel", imageUrl: "/images/paper-bags.png" },
    { name: "Servietten", slug: "servietten", description: "Individuell bedruckte Papierservietten", imageUrl: "/images/napkins.png" },
    { name: "Salatschalen", slug: "salatschalen", description: "Bedruckte Salatschalen mit Deckel", imageUrl: "/images/salad-bowls.png" },
    { name: "Einschlagpapier", slug: "einschlagpapier", description: "Bedrucktes fettdichtes Einschlagpapier", imageUrl: "/images/wrapping-paper.png" },
  ]).returning();

  const catMap: Record<string, number> = {};
  cats.forEach(c => { catMap[c.slug] = c.id; });

  await db.insert(products).values([
    {
      name: "Pappbecher Single Wall",
      slug: "pappbecher-single-wall",
      description: "Einwandige Pappbecher in verschiedenen Groessen, ideal fuer Kaffee und Heissgetraenke. Vollstaendig bedruckbar mit Ihrem Logo und Design. Hergestellt aus FSC-zertifiziertem Karton.",
      shortDescription: "Einwandige Pappbecher fuer Heissgetraenke mit individuellem Druck",
      categoryId: catMap["pappbecher"],
      imageUrl: "/images/paper-cups.png",
      basePrice: "0.08",
      minQuantity: 1000,
      material: "Karton",
      sizes: ["100ml", "200ml", "300ml", "400ml"],
      eco: true,
      featured: true,
    },
    {
      name: "Pappbecher Double Wall",
      slug: "pappbecher-double-wall",
      description: "Doppelwandige Pappbecher mit hervorragender Isolierung. Kein separater Sleeve notwendig. Premium-Haptik fuer anspruchsvolle Kunden.",
      shortDescription: "Doppelwandige Premium-Pappbecher ohne Sleeve",
      categoryId: catMap["pappbecher"],
      imageUrl: "/images/paper-cups.png",
      basePrice: "0.12",
      minQuantity: 500,
      material: "Karton",
      sizes: ["200ml", "300ml", "400ml", "500ml"],
      eco: true,
      featured: true,
    },
    {
      name: "Transparente Plastikbecher",
      slug: "transparente-plastikbecher",
      description: "Kristallklare Plastikbecher fuer Kaltgetraenke, Smoothies und Saefte. Vollstaendig bedruckbar mit Vollfarbdruck. Leichtes und bruchsicheres Material.",
      shortDescription: "Klare Becher fuer Kaltgetraenke und Smoothies",
      categoryId: catMap["plastikbecher"],
      imageUrl: "/images/plastic-cups.png",
      basePrice: "0.06",
      minQuantity: 1000,
      material: "PET",
      sizes: ["250ml", "400ml", "500ml", "700ml"],
      eco: false,
      featured: true,
    },
    {
      name: "Eisbecher Klassik",
      slug: "eisbecher-klassik",
      description: "Klassische Eisbecher aus hochwertigem Karton. Ideal fuer Gelato, Frozen Yogurt und Desserts. Lebensmittelecht und auslaufsicher.",
      shortDescription: "Klassische Eisbecher fuer Gelaterien und Cafes",
      categoryId: catMap["eisbecher"],
      imageUrl: "/images/ice-cream-cups.png",
      basePrice: "0.07",
      minQuantity: 1000,
      material: "Karton",
      sizes: ["80ml", "130ml", "200ml", "350ml"],
      eco: true,
      featured: false,
    },
    {
      name: "Takeaway Box Kraft",
      slug: "takeaway-box-kraft",
      description: "Stabile Takeaway-Boxen aus Kraft-Karton. Perfekt fuer warme Speisen, Salate und Bowls. Mit praktischem Klappdeckel und Beluerftungsloecher.",
      shortDescription: "Kraft-Boxen fuer warme und kalte Speisen",
      categoryId: catMap["lebensmittelboxen"],
      imageUrl: "/images/food-boxes.png",
      basePrice: "0.15",
      minQuantity: 500,
      material: "Kraft-Karton",
      sizes: ["500ml", "750ml", "1000ml", "1500ml"],
      eco: true,
      featured: true,
    },
    {
      name: "Burgerbox Premium",
      slug: "burgerbox-premium",
      description: "Premium Burgerboxen mit individuellem Druck. Perfekte Groesse fuer Burger, Sandwiches und Wraps. Stabiles und formbestaendiges Material.",
      shortDescription: "Premium Burgerboxen fuer Restaurants und Lieferdienste",
      categoryId: catMap["lebensmittelboxen"],
      imageUrl: "/images/food-boxes.png",
      basePrice: "0.18",
      minQuantity: 500,
      material: "Kraft-Karton",
      sizes: ["117x117x70mm", "117x117x80mm", "130x130x100mm"],
      eco: true,
      featured: false,
    },
    {
      name: "Papiertuete mit Henkel",
      slug: "papiertuete-mit-henkel",
      description: "Hochwertige Papiertueten mit gedrehten Henkeln. Ideal fuer Takeaway, Baeckereien und Einzelhandel. Bedruckbar mit Ihrem Logo in Vollfarbdruck.",
      shortDescription: "Tragbare Papiertueten fuer Takeaway und Retail",
      categoryId: catMap["papiertueten"],
      imageUrl: "/images/paper-bags.png",
      basePrice: "0.22",
      minQuantity: 500,
      material: "Kraft-Papier",
      sizes: ["18x8x22cm", "26x12x35cm", "32x14x42cm"],
      eco: true,
      featured: true,
    },
    {
      name: "Cocktailservietten",
      slug: "cocktailservietten",
      description: "Bedruckte Cocktailservietten fuer Bars, Restaurants und Events. 2-lagig, weich und saugfaehig. Vollstaendig individuell bedruckbar.",
      shortDescription: "2-lagige Cocktailservietten mit individuellem Druck",
      categoryId: catMap["servietten"],
      imageUrl: "/images/napkins.png",
      basePrice: "0.03",
      minQuantity: 2000,
      material: "Tissue-Papier",
      sizes: ["24x24cm", "33x33cm"],
      eco: true,
      featured: false,
    },
    {
      name: "Salatschale mit Deckel",
      slug: "salatschale-mit-deckel",
      description: "Bedruckte Salatschalen aus Karton mit transparentem Deckel. Perfekt fuer Salate, Bowls und kalte Speisen. Auslaufsicher und stapelbar.",
      shortDescription: "Bedruckte Schalen fuer Salate und Bowls",
      categoryId: catMap["salatschalen"],
      imageUrl: "/images/salad-bowls.png",
      basePrice: "0.20",
      minQuantity: 500,
      material: "Karton",
      sizes: ["500ml", "750ml", "1000ml"],
      eco: true,
      featured: true,
    },
    {
      name: "Fettdichtes Einschlagpapier",
      slug: "fettdichtes-einschlagpapier",
      description: "Bedrucktes fettdichtes Papier fuer Burger, Sandwiches, Wraps und Gebaeck. Lebensmittelecht und fettabweisend. Perfekt fuer den Foodservice.",
      shortDescription: "Fettdichtes Papier fuer Burger und Sandwiches",
      categoryId: catMap["einschlagpapier"],
      imageUrl: "/images/wrapping-paper.png",
      basePrice: "0.04",
      minQuantity: 1000,
      material: "Greaseproof-Papier",
      sizes: ["25x35cm", "30x40cm", "35x50cm"],
      eco: true,
      featured: false,
    },
    {
      name: "Papierstrohhalme",
      slug: "papierstrohhalme",
      description: "Biologisch abbaubare Papierstrohhalme mit individuellem Druck. Die umweltfreundliche Alternative zu Plastikstrohhalmen. Stabil und langlebig im Getraenk.",
      shortDescription: "Umweltfreundliche Papierstrohhalme mit Logo",
      categoryId: catMap["pappbecher"],
      imageUrl: "/images/paper-straws.png",
      basePrice: "0.02",
      minQuantity: 5000,
      material: "FSC-Papier",
      sizes: ["6x197mm", "6x230mm", "8x197mm"],
      eco: true,
      featured: false,
    },
  ]);
}
